# Generated by Django 4.0.7 on 2023-03-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='tags',
        ),
    ]
